config/routes.rb
Rails.application.routes.draw do
  root 'teachers#index'
resources :teachers do
	resources :schedules
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :teacher
    validates_uniqueness_of :teacher_id, scope: [:day, :time] 
  end

app/models/teacher.rb
class Teacher < ApplicationRecord

  GENDERS = [ "male", "female" ]
  ORDER_BY_FIELDS = [ "name", "dob", "gender" ]
  ORDER_BY = [ "Asc", "Desc" ]

	has_many :schedules

	def self.search params
    teachers = self
    if params[:q].present?
      teachers = teachers.where("name ilike ?", "%#{params[:q]}%")
    end
    if params[:start_date].present?
      teachers = teachers.where("dob >= ?", params[:start_date])
    end
    if params[:end_date].present?
      teachers = teachers.where("dob <= ?", params[:end_date])
    end
    if params[:order_by_field].present?
      order_by = params[:order_by] || "asc"
      order_by_field = params[:order_by_field]
      teachers = teachers.order("#{order_by_field} #{order_by}")
    end
    teachers.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
   @teacher=Teacher.find(params[:teacher_id])
    @schedules=@teacher.schedules
    @schedule=@schedules.build
  end
  def new
    @teacher=Teacher.find(params[:teacher_id])
    @schedules=@teacher.schedules
    @schedule=@schedules.build
  end
  def create
 	 @teacher=Teacher.find(params[:teacher_id])
    @schedules=@teacher.schedules
    @schedule=@schedules.build
  	@schedule.section=params[:schedule][:section]
  	@schedule.semester=params[:schedule][:semester]
  	@schedule.branch=params[:schedule][:branch]
    @schedule.day=params[:schedule][:day]
    @schedule.time=params[:schedule][:time] 
    @schedule.teacher_id=params[:schedule][:teacher_id]
  	if @schedule.save
      flash[:message] = "slot scheduled"
    else
      flash[:message] = "slot is not scheduled. Same day and time already exist"
    end
  	redirect_to teacher_schedules_url(teacher_id:@teacher)
  end
  def edit
     @teacher=Teacher.find(params[:teacher_id])
     @schedules=@teacher.schedules
    @schedule=@schedules.find(params[:id])
    
  end
  def update
  	 @teacher=Teacher.find(params[:teacher_id])
     @schedules=@teacher.schedules
    @schedule=@schedules.find(params[:id])
  	@schedule.section=params[:schedule][:section]
  	@schedule.semester=params[:schedule][:semester]
  	@schedule.branch=params[:schedule][:branch]
    @schedule.day=params[:schedule][:day]
  	@schedule.time=params[:schedule][:time]
  	@schedule.save
  	redirect_to teacher_schedules_url
  end
  def show
     @teacher=Teacher.find(params[:teacher_id])
     @schedules=@teacher.schedules
    @schedule=@schedules.find(params[:id])
  end
  def destroy
    @teacher=Teacher.find(params[:teacher_id])
    @schedules=@teacher.schedules
    @schedule=@schedules.find(params[:id])
    @schedule.destroy
    redirect_to teacher_schedules_url    
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def index
    @teachers = Teacher.search index_params
  end
  
  def new
  	@teacher=Teacher.new
  end

  def create
  	@teacher=Teacher.new(teacher_params)
  	@teacher.save
    redirect_to teachers_url
  end

  def edit
  end

  def update
     @teacher.update(teacher_params)
     @teacher.save
     redirect_to teachers_url
   end
  
  def show
  end
  
  def destroy
   @teacher.destroy
   redirect_to teachers_url
  end
 
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :gender, :dob)
  end

  def index_params
    params.permit(:q, :start_date, :end_date, :order_by_field, :order_by)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherSchedule</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/_schedule.html.erb
<%= form_for [@teacher,@schedule] do |f| %>
	
	<div class="field">
<%= f.label :branch%>
	<%= f.text_field :branch%>
</div>
	<div class="field">
	<%= f.label :semester%>
	<%= f.text_field :semester%>
</div>
<div class="field">
<%= f.label :section%>
	<%=f.text_field :section%>
</div>

<div class="field">
	<%= f.label :day%>
	<%= f.text_field :day%>
</div>
<div class="field">
	<%= f.label :time%>
	<%= f.text_field :time%>
</div>
    <div class="field">
	<%= f.hidden_field :teacher_id, value: @teacher.id %></div>
 
	<%= f.submit "submit"%>
</br></p>
<%end%>
<%=link_to 'back', teacher_schedules_url(teacher_id:@teacher)%>

app/views/schedules/edit.html.erb
<%= render partial: "schedule"%>

app/views/schedules/index.html.erb
<h1>Schedules#index</h1>
<% if flash[:message] %>
    <div class="message"><%= flash[:message] %></div>
  <% end %>
<%= form_for [@teacher,@schedule] do |f| %>
<p>
	<div class="field">
<%= f.label :branch%>
	<%= f.text_field :branch%>
</div>
	<div class="field">
	<%= f.label :semester%>
	<%= f.text_field :semester%>
</div>
<div class="field">
<%= f.label :section%>
	<%=f.text_field :section%>
</div>

<div class="field">
	<%= f.label :day%>
	<%= f.text_field :day%>
</div>
<div class="field">
	<%= f.label :time%>
	<%= f.text_field :time%>
</div>
    
 <div class="field">
	<%= f.hidden_field :teacher_id, value: @teacher.id %></div>
	<%= f.submit "submit"%>
</br></p>
<%end%>
<table>
<% @schedules.each do |schedule|%>
<% if schedule.persisted? %>
<tr><td>Branch</td>
	<td><%=schedule.branch%></td><td>Semester</td>
	<td><%=schedule.semester%></td>
	<td>Section</td>
	<td><%=schedule.section%></td>	 
	<td>Day</td>
	<td><%=schedule.day%></td>
	<td>Time</td>
	<td><%=schedule.time%></td>
	<td>Teacher Id</td>
	<td><%=schedule.teacher_id%> </td>
	<td><%=link_to 'edit',edit_teacher_schedule_url(@teacher.id,schedule.id)%></td>
	<td><%=link_to 'show',teacher_schedule_url(@teacher.id,schedule.id)%></td>
	<td><%=link_to 'delete',teacher_schedule_url(@teacher.id,schedule.id),method: 'delete'%><td> 
</tr>
<%end%>
<%end%>
</table>

app/views/schedules/new.html.erb
<%= render partial: "schedule"%>

app/views/schedules/show.html.erb
<table>
<tr><td>Branch:</td>
	<td><%=@schedule.branch%> </td>
	<td>Semester:</td>
	<td><%=@schedule.semester%> </td>
	<td>Section:</td>
	<td><%=@schedule.section%> </td>
	<td>Day:</td>
	<td><%=@schedule.day%> </td> 
	<td>Time:</td>
	<td><%=@schedule.time%> </td>
</tr>
</table>

app/views/teachers/_teacher.html.erb
<%=form_for(teacher) do |f|%>
  <p>
    <%=f.label :name%>
    <%=f.text_field :name%>
    <%=f.label :gender%>
    <%=f.select :gender, Teacher::GENDERS, prompt: true %>
    <%= f.label :dob%>
    <%= f.text_field :dob,  "data-provide" => 'datepicker' %>
    <%=f.submit "submit"%>
  </p>
<%end%>
<%=link_to 'back', teachers_url%>

app/views/teachers/edit.html.erb
<%= render 'teacher', teacher: @teacher %>

app/views/teachers/index.html.erb
<h1>Teachers#index</h1>
<%= form_tag(teachers_url, :method => "get", id: "search-form") do %>
  <%= text_field_tag(:q, params[:q]) %>
  <%= select_tag :order_by_field, options_for_select(Teacher::ORDER_BY_FIELDS, params[:order_by_field]), prompt: "Order Field" %>
  <%= select_tag(:order_by, options_for_select(Teacher::ORDER_BY, params[:order_by]), prompt: "Order By") %>
  <%= text_field_tag :start_date, params[:start_date], "data-provide" => 'datepicker' %>
  <%= text_field_tag :end_date, params[:end_date], "data-provide" => 'datepicker' %>
  <%= submit_tag "Search", :name => nil %>
<% end %>
<table>
<% @teachers.each do |teacher|%>
<% if teacher.persisted? %><tr><td>Name</td>
	<td><%=teacher.name%></td>
	<td>Gender</td>
	<td><%=teacher.gender%></td>
	<td>Date of Birth</td>
	<td><%=teacher.dob%></td>
	<td><%=link_to 'edit', edit_teacher_url(id:teacher.id)%></td>
	<td><%=link_to 'show',teacher_url(id:teacher.id)%></td>
    <td><%= link_to 'Destroy', teacher_url(id:teacher.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<td><%=link_to 'Add schedule for teacher', new_teacher_schedule_url(teacher_id:teacher.id)%></td>
</tr>
<%end%>
<%end%>
</table>
<%=link_to 'Add new teacher details', new_teacher_url%>

app/views/teachers/new.html.erb
<%= render 'teacher', teacher: @teacher %>

app/views/teachers/show.html.erb
<table>
<tr> <td>Name:</td>
	<td><%=@teacher.name%> </td>
	<td>Gender:</td>
	<td><%=@teacher.gender%> </td>
	<td>Date of Birth:</td>
	<td><%=@teacher.dob%> </td>
</tr>
</table>